Updated DDL including chanegs made to DB forced by limits
umgc/umgc.city.backend.web pull request #6
Opened 2020-04-13 03:06 UTC by CGilliland

Most changes were for field size.  Permit_type and application tables were combined with allowed_land_use table to bring row count own to 5,378 (max of 10,000 allowed).

2020-04-14 02:04 UTC, ahaile5 submitted a review, later dismissed

2020-04-15 12:26 UTC, krystina627 requested changes
Authorities table needs to be updated and the relationship between authorities and city_user should be going the other way. Also, please not the the relationship between zone_land_use table and allowed_land_use table is one to many. The ERD has it as one-to-one.

2020-04-15 12:26 UTC, krystina627 commented on src/main/resources/UMGCCity_DDL_master.sql
>      authority character varying(50) COLLATE pg_catalog."default" NOT NULL
Authorities table needs to change to mirror the authorities table in Prod. There are only two columns in this table now authority and id. The city_user table needs to be updated as well to include a authorities_id column that references the pk in authorities.

2020-04-16 02:57 UTC, CGilliland commented
I'm having issues getting to my charts so will have to update ERD tomorrow,
but I have a question.

"The relationship between zone_land_use table and allowed_land_use table is
one to many. The ERD has it as one-to-one."
The zone_land_use table is intended to be a lookup table for the
allowed_land_use table... isn't it correct that "one allowed_land_use can
be one type of zone_land_use ", making it a one to one?



On Wed, Apr 15, 2020, 8:26 AM Krystina Poling <notifications@github.com>
wrote:

> *@krystina627* requested changes on this pull request.
>
> Authorities table needs to be updated and the relationship between
> authorities and city_user should be going the other way. Also, please not
> the the relationship between zone_land_use table and allowed_land_use table
> is one to many. The ERD has it as one-to-one.
> ------------------------------
>
> In src/main/resources/UMGCCity_DDL_master.sql
> <https://github.com/umgc/umgc.city.backend.web/pull/6#discussion_r408797859>
> :
>
> > @@ -60,83 +65,87 @@ CREATE TABLE public.authorities
>      authority character varying(50) COLLATE pg_catalog."default" NOT NULL
>
> Authorities table needs to change to mirror the authorities table in Prod.
> There are only two columns in this table now authority and id. The
> city_user table needs to be updated as well to include a authorities_id
> column that references the pk in authorities.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/umgc/umgc.city.backend.web/pull/6#pullrequestreview-393718615>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFCMU3EMGA6VP4XLKUQWJDTRMWRW3ANCNFSM4MGVT3SQ>
> .
>

2020-04-17 03:41 UTC, ahaile5 submitted a review, later dismissed

2020-04-18 03:23 UTC, closed without merging